#define MAGIC_RANDOMIZATION_MIN	8
#define MAGIC_RANDOMIZATION_MAX	12

#define MANA_MAX 300
#define MANA_MIN 100
#define MANA_REGEN 1.8
#define MANA_REGEN_EXTRA 0.5
#define MANA_REGEN_MULTIPLIER 0.4
#define MANA_REGEN_COEFF 50

#define RESIDUAL_STAGE_1 1
#define RESIDUAL_STAGE_2 2
#define RESIDUAL_STAGE_3 3
#define RESIDUAL_STAGE_4 4

#define ui_mana "EAST-1:28,CENTER-5:10"
